### ISSUE TITLE
Restrictor Dropdown Tweak #2

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#24]
If the user has multiple search rows showing and deletes the Row 1, the search row taking its place (aka the New Row 1) should now only show 3 options: "for any of the words", "for all of the words", "for the exact phrase".

If the New Row 1 had exclusionary options ("excluding the words" or "excluding the phrase"), the drop-down should revert to the 1st option, "for any of the words".

Makes way more sense if you watch the video: https://ucsf.box.com/s/ii9wiatwzsryqobqsp2q

**Comment by Trott** [comment]
Done and up on the demo site.

**Comment by tmcdev** [comment]
Boom! You're the bomb :smiley_cat:

**Comment by tmcdev** [comment]
:bomb:
