### ISSUE TITLE
Get restrictor dropdown working

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#26]
Hook it up so restrictor dropdowns work:

![clip2](https://cloud.githubusercontent.com/assets/1381083/2897209/957e98d2-d57a-11e3-9058-34af72d182c3.png)

**The following key is based on how LTDL2 works; SOLR might parse queries differently ...**
- for any of the words = _any word in the text box_
- for all of the words = +foo AND +bar AND +beyond AND +belief
- for the exact phrase = "foo+bar+beyond+belief"
- excluding the words = -foo -bar
- excluding the phrase = -"foo+bar+beyond+belief"

**Comment by tmcdev** [comment]
Let's kill the exclusionary options ... no more 'excluding the words' or 'excluding the phrase'.

**Comment by Trott** [comment]
I'm going to move that last comment to a new ticket because, uh, it's already implemented. But we'll rip it out, no sweat.

**Comment by Trott** [comment]
All done and working on the demo page.
