### ISSUE TITLE
Get boolean dropdowns working

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#27]
Boolean search terms should work on the search row beneath it. The following should translate as **nico\* NOT (nicorette OR nicotine)**.

![clip3](https://cloud.githubusercontent.com/assets/1381083/2897262/0292d450-d57c-11e3-8dbe-293ec128ef4c.png)

**Comment by Trott** [comment]
What are the rules for precedence? How would I know that the above wouldn't translate to simply `nico* NOT nicorette OR nicotine`? (Although, for all I know, as far as Solr is concerned, that's equivalent to what you wrote above. But I imagine we want the parentheses in there after the user hits search and we rewrite the query for them per the wireframes.)

**Comment by tmcdev** [comment]
Hmmm ... I want to follow Google rules since our novices are used to that search experience, but I don't want to change the rules for our experts ...

/cc @tuolumne @rebeccatang @gboushey

**Comment by tmcdev** [comment]
Awaiting input from Rachel T...

**Comment by tmcdev** [comment]
Final decision on hold; for now please follow strict Boolean algebra rules, and parse the query as entered.

**Comment by Trott** [comment]
For the record, my preference is: Just let the chips fall where they fall and let's sort out problems (if any) as we find them. No parentheses.
