### ISSUE TITLE
Test handling of special chars

### ISSUE THREAD

**Issue by Trott** [Trott/ltdl3-client#29]
```
+ - && || ! ( ) { } [ ] ^ " ~ * ? : \
```

http://lucene.apache.org/core/3_6_0/queryparsersyntax.html#Escaping%20Special%20Characters

**Comment by Trott** [comment]
I do like how the last two characters look like a somewhat unhappy face

: \

**Comment by rebeccatang** [comment]
It's a meh face :)

On May 15, 2014, at 5:04 PM, "Rich Trott" <notifications@github.com<mailto:notifications@github.com>> wrote:

I do like how the last two characters look like a somewhat unhappy face

: \

**Comment by Trott** [comment]
#51 took care of this, although it may not handle them all in the desired way.
