### ISSUE TITLE
Query, search results should hang around on refresh

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#41]
Refreshing the browser should not delete the query or list of results.

**Comment by Trott** [comment]
Related: search results should be bookmark-able (using _bookmark_ the way everyone else on the planet uses it, and not some idiosyncratic LTDL-specific thing)

**Comment by tmcdev** [comment]
Right! Does that need to be a separate issue?

**Comment by Trott** [comment]
No, the same thing will solve both of those problems.
