### ISSUE TITLE
Type & Brand Name Flow: Restrictor Dropdown Fix

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#5]
If the user selects a pre-defined TYPE or BRAND NAME in the 1st dropdown menu, the 2nd dropdown (the restrictor dropdown) should disable.

Editing the pre-filled text will re-enable the restrictor dropdown. See attached PNG, and prototype screen http://invis.io/VPSNBY3X for clarity.

![type-brand-drops](https://cloud.githubusercontent.com/assets/1381083/2796350/7ab89fe2-cc0c-11e3-8a2e-9bf8e8e40916.png)

**Comment by Trott** [comment]
This is fixed now.
