### ISSUE TITLE
Restrictor Dropdown Modification for Search Rows 2 thru Infinity

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#6]
Search Rows 2 thru [X] contain additional values in the Restrictor Dropdown menu. See attached PNG, and prototype screen http://invis.io/M2SNGO6D for clarity.

![restrictors](https://cloud.githubusercontent.com/assets/1381083/2796377/6c98488a-cc0d-11e3-86ae-c13888c1faee.png)

**Comment by Trott** [comment]
Fixed!
