### ISSUE TITLE
STOP THE PRESSES!

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#60]
User testing has revealed that our lovely little builder requires a major rethink. I don't want you going all out (especially with one hand) on a component that might soon die a brutal death.

If the work that you're doing will apply to any version of a search box, then by all means carry on.

**Comment by tmcdev** [comment]
This probably shouldn't be an issue, but I couldn't find a way to comment on the whole project soo ... yeah.

**Comment by Trott** [comment]
The only remaining issues that I have open are trivial little things that are on a component that should be re-usable by anything we do, but I'll refrain from busting my hump on anything.
